/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import  { useRef, useEffect } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
//animate
import {a} from '@react-spring/three';


import cubeScene from '../assets/3d/cubes.glb';


const Cube =  (props) => {
  
  const cubeRef = useRef();
  const { nodes, materials } = useGLTF(cubeScene)
  return (
    <a.group ref={cubeRef} {...props}>
      <OrthographicCamera
        makeDefault={false}
        far={100}
        near={0.01}
        position={[-2.841, 1.179, 0.248]}
        rotation={[-1.629, -1.208, 0.576]}
      />
      <mesh
        geometry={nodes['Part5-2'].geometry}
        material={materials['polished aluminum']}
        position={[0.338, 0.037, 0.239]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part6-1'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.329, 0.039, 0.243]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part6-8'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.344, -0.029, 0.325]}
        rotation={[2.585, 1.157, -1.191]}
      />
      <group position={[0.359, 0.05, 0.315]} rotation={[-0.145, 0.382, 2.98]}>
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
        />
        <mesh
          geometry={nodes.mesh_3_1.geometry}
          material={materials['blue satin finish plastic-1']}
        />
        <mesh
          geometry={nodes.mesh_3_2.geometry}
          material={materials['sandblasted aluminum-1']}
        />
      </group>
      <mesh
        geometry={nodes['Part5-3'].geometry}
        material={materials['polished aluminum']}
        position={[0.256, 0.056, 0.27]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part9-1'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.335, 0.036, 0.23]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part9-2'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.252, 0.055, 0.261]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part6-3'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.235, -0.019, 0.289]}
        rotation={[2.585, 1.157, -1.191]}
      />
      <mesh
        geometry={nodes['Part6-4'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.262, -0.01, 0.356]}
        rotation={[2.585, 1.157, -1.191]}
      />
      <mesh
        geometry={nodes['Part6-6'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.316, -0.048, 0.261]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part6-7'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.317, -0.038, 0.259]}
        rotation={[2.585, 1.157, -1.191]}
      />
      <mesh
        geometry={nodes['Part9-5'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.272, -0.02, 0.361]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part7-2'].geometry}
        material={materials['polished aluminum-3']}
        position={[0.356, 0.049, 0.309]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part9-9'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.321, -0.052, 0.248]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <group position={[0.333, 0.049, 0.248]} rotation={[-1.776, 0.15, -2.755]}>
        <mesh
          geometry={nodes.mesh_14.geometry}
          material={nodes.mesh_14.material}
        />
        <mesh
          geometry={nodes.mesh_14_1.geometry}
          material={materials['sandblasted aluminum']}
        />
        <mesh
          geometry={nodes.mesh_14_2.geometry}
          material={materials['blue satin finish plastic']}
        />
      </group>
      <mesh
        geometry={nodes['Part5-5'].geometry}
        material={materials['polished aluminum']}
        position={[0.325, -0.05, 0.257]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part9-6'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.355, -0.04, 0.331]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        geometry={nodes['Part9-3'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.286, 0.067, 0.343]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        
        
        geometry={nodes['Part9-7'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.239, -0.032, 0.279]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <group position={[0.25, 0.059, 0.28]} rotation={[-0.556, -1.157, -1.951]}>
        <mesh
          
          
          geometry={nodes.mesh_19.geometry}
          material={nodes.mesh_19.material}
        />
        <mesh
          
          
          geometry={nodes.mesh_19_1.geometry}
          material={materials['sandblasted aluminum']}
        />
        <mesh
          
          
          geometry={nodes.mesh_19_2.geometry}
          material={materials['blue satin finish plastic']}
        />
      </group>
      <group position={[0.245, -0.029, 0.295]} rotation={[1.365, -0.15, -0.387]}>
        <mesh
          
          
          geometry={nodes.mesh_20.geometry}
          material={nodes.mesh_20.material}
        />
        <mesh
          
          
          geometry={nodes.mesh_20_1.geometry}
          material={materials['sandblasted aluminum']}
        />
        <mesh
          
          
          geometry={nodes.mesh_20_2.geometry}
          material={materials['blue satin finish plastic']}
        />
      </group>
      <mesh
        
        
        geometry={nodes['Part6-5'].geometry}
        material={materials['polished aluminum-1']}
        position={[0.343, -0.038, 0.327]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <group position={[0.328, -0.039, 0.263]} rotation={[2.585, 1.157, -1.191]}>
        <mesh
          
          
          geometry={nodes.mesh_22.geometry}
          material={nodes.mesh_22.material}
        />
        <mesh
          
          
          geometry={nodes.mesh_22_1.geometry}
          material={materials['sandblasted aluminum']}
        />
        <mesh
          
          
          geometry={nodes.mesh_22_2.geometry}
          material={materials['blue satin finish plastic']}
        />
      </group>
      <mesh
        
        
        geometry={nodes['Part5-4'].geometry}
        material={materials['polished aluminum']}
        position={[0.243, -0.031, 0.288]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <mesh
        
        
        geometry={nodes['Part9-4'].geometry}
        material={materials['polished aluminum-2']}
        position={[0.368, 0.048, 0.313]}
        rotation={[-1.776, 0.15, -2.755]}
      />
      <group position={[0.318, -0.038, 0.26]} rotation={[2.997, -0.382, -2.98]}>
        <mesh
          
          
          geometry={nodes.mesh_25.geometry}
          material={nodes.mesh_25.material}
        />
        <mesh
          
          
          geometry={nodes.mesh_25_1.geometry}
          material={materials['blue satin finish plastic-1']}
        />
        <mesh
          
          
          geometry={nodes.mesh_25_2.geometry}
          material={materials['sandblasted aluminum-1']}
        />
      </group>
      <mesh
        
        
        geometry={nodes['part13-1'].geometry}
        material={materials['brushed steel']}
        position={[0.321, -0.034, 0.273]}
        rotation={[-0.242, -1.187, -1.661]}
      />
      <group position={[0.347, 0.045, 0.286]} rotation={[2.997, -0.382, 1.738]}>
        <mesh
          
          
          geometry={nodes.mesh_27.geometry}
          material={nodes.mesh_27.material}
        />
        <mesh
          
          
          geometry={nodes.mesh_27_1.geometry}
          material={materials['matte steel']}
        />
        <mesh
          
          
          geometry={nodes.mesh_27_2.geometry}
          material={materials['green low gloss plastic']}
        />
      </group>
      <mesh
        
        
        geometry={nodes['part13-3'].geometry}
        material={materials['brushed steel']}
        position={[0.333, 0.039, 0.257]}
        rotation={[1.915, 0.863, -0.611]}
      />
      <mesh
        
        
        geometry={nodes['part16-1'].geometry}
        material={materials['matte steel-1']}
        position={[0.263, 0.067, 0.276]}
        rotation={[-0.177, 0.187, -0.152]}
      />
      <group position={[0.27, -0.012, 0.349]} rotation={[2.997, -0.382, -1.409]}>
        <mesh
          
          
          geometry={nodes.mesh_30.geometry}
          material={nodes.mesh_30.material}
        />
        <mesh
          
          
          geometry={nodes.mesh_30_1.geometry}
          material={materials['satin finish bronze']}
        />
        <mesh
          
          
          geometry={nodes.mesh_30_2.geometry}
          material={materials['blue low gloss plastic']}
        />
        <mesh
          
          
          geometry={nodes.mesh_30_3.geometry}
          material={materials['matte silver']}
        />
        <mesh
          
          
          geometry={nodes.mesh_30_4.geometry}
          material={materials['brushed chromium']}
        />
      </group>
      <group position={[0.322, 0.02, 0.288]} rotation={[-1.46, 0.271, 1.89]}>
        <mesh
          
          
          geometry={nodes.mesh_31.geometry}
          material={materials['matte nickel']}
        />
        <mesh
          
          
          geometry={nodes.mesh_31_1.geometry}
          material={materials.color}
        />
      </group>
      <mesh
        
        
        geometry={nodes['part13-2'].geometry}
        material={materials['brushed steel']}
        position={[0.263, 0.055, 0.283]}
        rotation={[1.865, 0.813, -0.574]}
      />
      <mesh
        
        
        geometry={nodes['part16-2'].geometry}
        material={materials['matte steel-1']}
        position={[0.318, -0.046, 0.27]}
        rotation={[-0.364, -0.807, 2.924]}
      />
      <mesh
        
        
        geometry={nodes['part13-4'].geometry}
        material={materials['brushed steel']}
        position={[0.252, -0.018, 0.299]}
        rotation={[2.367, 1.109, -0.993]}
      />
      <group position={[0.318, -0.005, 0.293]} rotation={[-1.847, 0.127, 1.968]}>
        <mesh
          
          
          geometry={nodes.mesh_35.geometry}
          material={materials['matte nickel']}
        />
        <mesh
          
          
          geometry={nodes.mesh_35_1.geometry}
          material={materials.color}
        />
      </group>
    </a.group>
  )
}



export default Cube; 
